apiVersion: v2
name: geosupport
description: Geosupport is New York City's geocoder of record created by the Department of City Planning

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# Geosupport artifacts use the following syntax: <release>_<version>
# where (in pseudo date/regex syntax)
#   release: YY[a-z][1-9]?
#   version: YY\.[0-9]+
appVersion: 20a_20.1
