baseURL = "/"
languageCode = "en-us"
theme = "hugo-whisper-theme"
#theme = "mainroad"
themesDir = "themes"
title = "Geoclient"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]

  geoclient_version="2.0.0-rc.7"
  geoclient_repository= "https://github.com/CityOfNewYork/geoclient"
  geosupport_version = "20.2"
  geosupport_release = "20B"

  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Geoclient provides a RESTful interface for accessing the Department of City Planning&apos;s Geosupport application.'
  homepage_image = '/images/runtime.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://github.com/mlipper/bleat"
    meta_og_image = "/images/logo.png"
    #meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Bleat is a farm for goats."
    meta_twitter_card = "summary"
    meta_twitter_site = "@MatthewLipper"
    meta_twitter_creator = "@MatthewLipper"

  [params.logo]
      #mobile = "/images/logo-mobile.svg"
      #standard  = "/images/logo.svg"
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"
